package com.example.utils

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    BANGLA("bn", "বাংলা")
}

data class AppStrings(
    val appTitle: String,
    val appTagline: String,
    val monthlySalarySection: String,
    val basicSalary: String,
    val basicSalaryHint: String,
    val basicSalaryRequired: String,
    val allowancesSection: String,
    val housingAllowance: String,
    val medicalAllowance: String,
    val transportAllowance: String,
    val otherAllowance: String,
    val addAllowance: String,
    val deductionsSection: String,
    val providentFund: String,
    val incomeTax: String,
    val otherDeduction: String,
    val addDeduction: String,
    val taxNote: String,
    val takeHomeSalary: String,
    val grossSalary: String,
    val totalDeductions: String,
    val annualGross: String,
    val annualTakeHome: String,
    val salaryBreakdown: String,
    val warningDeductionExceedsGross: String,
    val reset: String,
    val resetConfirmTitle: String,
    val resetConfirmMessage: String,
    val confirm: String,
    val cancel: String,
    val addCustomAllowanceTitle: String,
    val addCustomDeductionTitle: String,
    val itemName: String,
    val itemAmount: String,
    val add: String,
    val remove: String,
    val shareBreakdown: String,
    val copiedToClipboard: String,
    val optionalZeroDefault: String,
    val netSalaryBadge: String
)

object LocalizationManager {

    private val englishStrings = AppStrings(
        appTitle = "BD Salary Calculator",
        appTagline = "Quick salary & take-home breakdown for Bangladesh",
        monthlySalarySection = "Monthly Salary Details",
        basicSalary = "Basic Salary",
        basicSalaryHint = "e.g. 30,000",
        basicSalaryRequired = "Required",
        allowancesSection = "Allowances",
        housingAllowance = "Housing Allowance",
        medicalAllowance = "Medical Allowance",
        transportAllowance = "Transport Allowance",
        otherAllowance = "Other Allowance",
        addAllowance = "+ Add Allowance",
        deductionsSection = "Deductions",
        providentFund = "Provident Fund (PF)",
        incomeTax = "Income Tax Deduction",
        otherDeduction = "Other Deduction",
        addDeduction = "+ Add Deduction",
        taxNote = "Enter your actual estimated monthly tax deduction. Tax rules may vary by income, exemptions, and applicable regulations.",
        takeHomeSalary = "Take-home Salary",
        grossSalary = "Gross Salary",
        totalDeductions = "Total Deductions",
        annualGross = "Annual Gross",
        annualTakeHome = "Annual Take-home",
        salaryBreakdown = "Salary Summary",
        warningDeductionExceedsGross = "Deductions cannot be higher than gross salary.",
        reset = "Reset",
        resetConfirmTitle = "Reset Calculator?",
        resetConfirmMessage = "This will clear all entered salary and allowance amounts.",
        confirm = "Reset",
        cancel = "Cancel",
        addCustomAllowanceTitle = "Add Custom Allowance",
        addCustomDeductionTitle = "Add Custom Deduction",
        itemName = "Item Name",
        itemAmount = "Amount (৳)",
        add = "Add",
        remove = "Remove",
        shareBreakdown = "Share Breakdown",
        copiedToClipboard = "Salary breakdown copied to clipboard",
        optionalZeroDefault = "Defaults to ৳0",
        netSalaryBadge = "Net Pay"
    )

    private val banglaStrings = AppStrings(
        appTitle = "বেতন ক্যালকুলেটর",
        appTagline = "বাংলাদেশে মাসিক বেতন, ভাতা ও কর্তনের হিসাব",
        monthlySalarySection = "মাসিক বেতনের বিবরণ",
        basicSalary = "মূল বেতন",
        basicSalaryHint = "যেমন: ৩০,০০০",
        basicSalaryRequired = "আবশ্যক",
        allowancesSection = "ভাতা সমূহ",
        housingAllowance = "বাড়ি ভাড়া ভাতা",
        medicalAllowance = "চিকিৎসা ভাতা",
        transportAllowance = "যাতায়াত ভাতা",
        otherAllowance = "অন্যান্য ভাতা",
        addAllowance = "+ ভাতা যোগ করুন",
        deductionsSection = "কর্তন সমূহ",
        providentFund = "প্রভিডেন্ট ফান্ড (পিএফ)",
        incomeTax = "আয়কর কর্তন",
        otherDeduction = "অন্যান্য কর্তন",
        addDeduction = "+ কর্তন যোগ করুন",
        taxNote = "আপনার প্রযোজ্য আনুমানিক মাসিক আয়কর কর্তনের পরিমাণ লিখুন। আয়, করমুক্ত সীমা ও প্রযোজ্য নিয়ম অনুযায়ী করের পরিমাণ পরিবর্তিত হতে পারে।",
        takeHomeSalary = "হাতে পাওয়া বেতন",
        grossSalary = "মোট বেতন",
        totalDeductions = "মোট কর্তন",
        annualGross = "বার্ষিক মোট বেতন",
        annualTakeHome = "বার্ষিক হাতে পাওয়া বেতন",
        salaryBreakdown = "বেতনের সংক্ষিপ্ত বিবরণ",
        warningDeductionExceedsGross = "মোট কর্তনের পরিমাণ মোট বেতনের চেয়ে বেশি হতে পারে না।",
        reset = "রিসেট",
        resetConfirmTitle = "রিসেট করবেন?",
        resetConfirmMessage = "এটি আপনার প্রবেশ করানো সকল বেতনের পরিমাণ মুছে ফেলবে।",
        confirm = "রিসেট করুন",
        cancel = "বাতিল",
        addCustomAllowanceTitle = "নতুন ভাতা যোগ করুন",
        addCustomDeductionTitle = "নতুন কর্তন যোগ করুন",
        itemName = "ভাতা/কর্তনের নাম",
        itemAmount = "পরিমাণ (৳)",
        add = "যোগ করুন",
        remove = "মুছুন",
        shareBreakdown = "শেয়ার করুন",
        copiedToClipboard = "বেতনের বিবরণ ক্লিপবোর্ডে কপি করা হয়েছে",
        optionalZeroDefault = "ঐচ্ছিক (৳০)",
        netSalaryBadge = "নেট বেতন"
    )

    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> englishStrings
            AppLanguage.BANGLA -> banglaStrings
        }
    }
}
